INSERT INTO resource_reviews (user_id, like, rating, resource_id, comment, pin)
VALUES (25, TRUE, 4, 23, 'This was perfect for me!', TRUE),
VALUES (20, 3, 23, 'Was useful, but could have been better'),
VALUES (20, TRUE, 4, 21, 'WOOOOOOWW, exactly what I was looking for.', TRUE),
VALUES (19, TRUE, 4, 5, 'This was perfect for me!'),
VALUES (15, 3, 12, 'Was useful, but could have been better'),
VALUES (10, TRUE, 2, 10, 'This was perfect for me!'),
VALUES (12, 2, 8, 'Was useful, but could have been better'),
VALUES (9, TRUE, 4, 9, 'WOOOOOOWW, exactly what I was looking for.', TRUE),
VALUES (1, TRUE, 3, 11, 'Was useful, but could have been better'),
VALUES (2, TRUE, 4, 16, 'WOOOOOOWW, exactly what I was looking for.', TRUE),
VALUES (30, 1, 5, 'Trash. Absolute Trash'),
VALUES (21, TRUE, 4, 16, 'This resource is aight', TRUE),
VALUES (19, TRUE, 5, 42, 'Dang I loved everything about this', TRUE),
VALUES (9, 3, 50, 'Can we not post trash here jeez'),
VALUES (5, TRUE, 4, 55, 'Not bad'),
VALUES (1, 3, 49, "In support of it’s usefullness although I would not keep using this again and again"),
VALUES (2, TRUE, 5, 60, 'LOVE IT', TRUE),
VALUES (19, TRUE, 4.0, 29, "Great source I’m a true learner!", TRUE),
VALUES (15, 2, 47, 'Bonkers wtf is this'),
VALUES (23, TRUE, 4, 53, 'YES!!!', TRUE),
VALUES (7, TRUE, 4, 59, 'Really loved this resource', TRUE),
VALUES (10, 2, 23, 'Hmmm not really useful for me'),
VALUES (6, TRUE, 5, 45, 'WOW, such amazing content!', TRUE),
VALUES (23, TRUE, 4, 17, NULL, TRUE),
VALUES (11, TRUE, 3, 21, 'It was okay... I guess'),
VALUES (23, 1, 27, 'JUST TERRIBLE!'),
VALUES (4, TRUE, 4, 34, 'The content was so amazing!', TRUE),
VALUES (16, TRUE, 3, 37, 'Average...'),
VALUES (19, 2, 41, 'Not impressed!'),
VALUES (12, TRUE, 5, 45, 'OMG WOOOOWW!', TRUE);
